name: Latest

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Clean build
        run: ./naul.sh clean
      
      - name: Generate iso
        run: ./naul.sh iso
      
      - name: Update release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Latest
          files: naul.iso
          make_latest: false
          generate_release_notes: false
          overwrite_files: true
