name: Latest

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: Move latest tag
        run: |
          git tag -f latest "$GITHUB_SHA"
          git push origin latest --force
      
      - name: Generate v1 iso
        run: |
          ./naul.sh clean
          X86_64_LEVEL=1 ./naul.sh iso
          mv naul.iso naul-v1.iso
      
      - name: Generate v2 iso
        run: |
          ./naul.sh clean
          X86_64_LEVEL=2 ./naul.sh iso
          mv naul.iso naul-v2.iso

      - name: Generate main iso
        run: |
          ./naul.sh clean
          ./naul.sh iso
      
      - name: Update release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Latest
          make_latest: true
          generate_release_notes: false
          files: |
            naul-v1.iso
            naul-v2.iso
            naul.iso
